/*
 * This source file was generated by the Gradle 'init' task
 */
package DomusControl;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

import DomusControl.exceptions.DomusControlException;
import DomusControl.exceptions.casa.CasaJaExisteException;
import DomusControl.exceptions.casa.CasaNaoExisteException;
import DomusControl.exceptions.casa.UtilizadorJaExisteExecption;
import DomusControl.exceptions.casa.UtilizadorNaoExisteException;
import DomusControl.home.Casa;
import DomusControl.services.DivisaoInfo;
import DomusControl.ui.interfaces_genericas.ThrowingBiConsumer;
import DomusControl.ui.interfaces_genericas.ThrowingBiFunction;
import DomusControl.ui.interfaces_genericas.ThrowingConsumer;
import DomusControl.ui.interfaces_genericas.ThrowingFunction;
import DomusControl.users.CasaAcesso;
import DomusControl.users.Papel;
import DomusControl.users.Utilizador;

public class DomusControl implements Serializable {
    private Map<String,Casa> casas; // casa é identificada pelo nome (tmb é único)
    private Map<String,Utilizador> utilizadores; // o utilizador é identificado pelo email (tmb é único)

    public DomusControl() {
        this.casas = new HashMap<>();
        this.utilizadores = new HashMap<>();
    }

    public DomusControl(Map<String,Casa> c, Map<String,Utilizador> u) {
        this.setCasas(c);
        this.setUtilizadores(u);
    }

    //método importante para ler estados de um ficheiro
    public DomusControl(DomusControl umaApp) {    //este getters já fazem as cópias necessárias para a composição
        this.casas = umaApp.getCasas();
        this.utilizadores = umaApp.getUtilizadores();
    }

    public Map<String,Casa> getCasas() {
       Map<String,Casa> res = new HashMap<>();

        for (Map.Entry<String,Casa> entradas: this.casas.entrySet()) {
            res.put(entradas.getKey(), entradas.getValue().clone());
        }
        return res;
    }

    public void setCasas(Map<String,Casa> casas) {
        this.casas = new HashMap<>();

        for (Map.Entry<String,Casa> entradas: casas.entrySet()) {
            this.casas.put(entradas.getKey(), entradas.getValue().clone());
        }
    }

    public Map<String,Utilizador> getUtilizadores() {
        Map<String,Utilizador> res = new HashMap<>();

        for (Map.Entry<String,Utilizador> entradas: this.utilizadores.entrySet()) {
            res.put(entradas.getKey(), entradas.getValue().clone());
        }
        return res;
    }

    public void setUtilizadores(Map<String, Utilizador> utilizadores) {
        this.utilizadores = new HashMap<>();

        for (Map.Entry <String,Utilizador> entradas: utilizadores.entrySet()) {
            this.utilizadores.put(entradas.getKey(), entradas.getValue().clone());
        }
    }

    // quem cria a casa fica automaticamente como admin da mesma
    public void addCasa(String email, String nomeCasa) throws DomusControlException {
        if (this.casas.containsKey(nomeCasa)) {
            throw new CasaJaExisteException(nomeCasa);
        }

        Utilizador u = this.utilizadores.get(email);
        if (u == null) {
            throw new UtilizadorNaoExisteException(email);
        }

        Casa casa = new Casa(nomeCasa);

        casa.addUtilizador(u, Papel.ADMIN);
        this.casas.put(nomeCasa, casa);
    }

    public void addUtilizador(String nome,String email) throws DomusControlException {
        if (this.utilizadores.containsKey(email)) {
            throw new UtilizadorJaExisteExecption(email);
        }

        Utilizador user = new Utilizador(nome, email);

        this.utilizadores.put(email,user);
    }
    
    public Utilizador getUtilizador(String email) throws DomusControlException {
        Utilizador user = this.utilizadores.get(email);

        if (user == null) {
            throw new UtilizadorNaoExisteException(email);
        }

        return user.clone();
    }   

    public Casa getCasa(String nome) throws DomusControlException {
        Casa casa = this.casas.get(nome);

        if (casa == null) {
            throw new CasaNaoExisteException(nome);
        }

        return casa.clone();
    }

    // métodos privados para obter a casa e o utilizar interno
    private Casa obterCasaInterna(String nomeCasa) throws CasaNaoExisteException {
        Casa casa = this.casas.get(nomeCasa);
        if (casa == null) {
            throw new CasaNaoExisteException(nomeCasa);
        }
        return casa;
    }

    private Utilizador obterUtilizadorInterno(String email) throws UtilizadorNaoExisteException {
        Utilizador utilizador = this.utilizadores.get(email);
        if (utilizador == null) {
            throw new UtilizadorNaoExisteException(email);
        }
        return utilizador;
    }

    public int getNumeroUtilizadores() {
        return this.utilizadores.size();
    }

    public int getNumeroCasas() {
        return this.casas.size();
    }

    public void executarNaCasa(String nomeCasa, ThrowingConsumer<Casa> operacao) throws DomusControlException {
        Casa casa = obterCasaInterna(nomeCasa);
        operacao.accept(casa);
    }

    public void executarNaCasa(String nomeCasa, String email, ThrowingBiConsumer<Casa,Utilizador> operacao) throws DomusControlException {
        Casa casa = obterCasaInterna(nomeCasa);
        Utilizador utilizador = obterUtilizadorInterno(email);
        operacao.accept(casa, utilizador);
    }

    public <T> T consultarCasa(String nomeCasa, ThrowingFunction<Casa,T> operacao) throws DomusControlException {
        Casa casa = obterCasaInterna(nomeCasa);
        return operacao.apply(casa);
    }

    public <T> T consultarCasa(String nomeCasa,String email, ThrowingBiFunction<Casa, Utilizador, T> operacao) throws DomusControlException {
        Casa casa = obterCasaInterna(nomeCasa);
        Utilizador utilizador = obterUtilizadorInterno(email);
        return operacao.apply(casa, utilizador);
    }

    // obtém número de elementos que obdece à função passada
    public int getNumero(String nomeCasa, Function<Casa, Integer> function) {
        return function.apply(this.casas.get(nomeCasa));
    }

    //Métodos de "querys" sobre conjuntos de casas
    public Casa getCasaComMaiorConsumo() {
        Optional<Casa>  casaMaiorConsumo = this.casas.values().stream()
                                                 .sorted((casa1,casa2) -> Double.compare(casa2.getConsumoTotalCasa(), casa1.getConsumoTotalCasa()))
                                                 .findFirst();

        return casaMaiorConsumo.isPresent() ? casaMaiorConsumo.get().clone() : null;
    }

    // Retorna 3 divisões e respetiva casa com mais dispositivos
    public List<DivisaoInfo> getTopTresDivisoesComMaisDipositivos() throws DomusControlException {
        List<DivisaoInfo> aux = new ArrayList<>();

        for (Casa casa : this.casas.values()) {
            for (String div : casa.getDivisoes().keySet()) {
                aux.add(new DivisaoInfo(casa, div));
            }
        }
                              
        return aux.stream()
                          .sorted((d1,d2) -> Integer.compare(d2.getNumDispositivos(),
                                                            d1.getNumDispositivos()))        
                           .limit(3)
                           .collect(Collectors.toList());
    }

    // devolve o utilizador que é dono (papel de admin) em mais casas
    public Utilizador utilizadorComMaisCasasComoAdmin() {
        // Map para contar quantas vezes cada utilizador é ADMIN
        Map<Utilizador, Integer> adminCount = new HashMap<>();
        
        for (Casa casa : this.casas.values()) {
            for (CasaAcesso acesso : casa.getAcessos()) {

                if (acesso.isAdmin()) {
                    Utilizador user = acesso.getUtilizador();
                    
                    int count = adminCount.containsKey(user) ? adminCount.get(user) + 1 : 1;
                    adminCount.put(user,count);
                }
            }
        }        

        return adminCount.entrySet().stream()
                                    .max((e1,e2) -> Integer.compare(e1.getValue(), e2.getValue()))
                                    .map(entry -> entry.getKey().clone())
                                    .orElse(null);
    }

    public boolean equals(Object o) {
        if (this == o) 
            return true;

        if (o == null || this.getClass() != o.getClass()) 
            return false;

        DomusControl app = (DomusControl) o;
        return this.casas.equals(app.getCasas()) && 
               this.utilizadores.equals(app.getUtilizadores());
    }

    public DomusControl clone() {
        return new DomusControl(this);
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("App = [");

        for (Casa c : this.casas.values()) {
            sb.append(c.toString());
        }

        for (Utilizador u : this.utilizadores.values()) {
            sb.append(u.toString());
        }

         sb.append("];\n");

         return sb.toString();
    }

    public void guardarEstado(String ficheiro) throws FileNotFoundException,
                                                      IOException{
        FileOutputStream fos = new FileOutputStream(ficheiro);
        ObjectOutputStream oos = new ObjectOutputStream (fos);
        oos.writeObject(this);
        oos.flush();
        oos.close();
    }

    public static DomusControl carregaEstado(String ficheiro) throws FileNotFoundException,
                                                                     IOException,
                                                                     ClassNotFoundException {
            FileInputStream fis = new FileInputStream(ficheiro);
            ObjectInputStream ois = new ObjectInputStream(fis);
            DomusControl app = (DomusControl) ois.readObject();
            ois.close();
            
            return app;
        }
    }

